"""
Django settings for gest_coop project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rid@@4a2h2j1--gp&zw7br-wvk#^e60w67yn&a*6@6di)9*ta+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #app
    'pages',
    'authentication',
    'crispy_forms',
    'crispy_bootstrap5',
    'products',
    'orders',
    'training',
    'production_tracking',
    'members',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = 'bootstrap5'


STRIPE_PUBLIC_KEY = 'pk_test_51OoXavDhxsvMurA1y6quM0ZxIIU4W3XAgal8y2PqGHhuGKabdgerXVBEllccx6I5yFswwJF8Jz6vaE57S637Alfm00NlrWcKZfpk_test_51OoXavDhxsvMurA1y6quM0ZxIIU4W3XAgal8y2PqGHhuGKabdgerXVBEllccx6I5yFswwJF8Jz6vaE57S637Alfm00NlrWcKZfpk_test_51OoXavDhxsvMurA1y6quM0ZxIIU4W3XAgal8y2PqGHhuGKabdgerXVBEllccx6I5yFswwJF8Jz6vaE57S637Alfm00NlrWcKZf'
STRIPE_SECRET_KEY = 'sk_test_51OoXavDhxsvMurA1oeMDrk49tgXfPJbrBMYwJAzL3GocnBuXIfgnm2H2dWCCBGj2fMssWJhoINQcxdZbLhJgmWzO00KhYA5aT0'
#parametre envoie email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'  # L'utilisateur SMTP pour SendGrid est toujours 'apikey'
EMAIL_HOST_PASSWORD = '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'
DEFAULT_FROM_EMAIL = 'GestCoop <ziouboup@gmail.com>'



# gest_coop/settings.py

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULE = {
    'update_production_tracking': {
        'task': 'production_tracking.tasks.update_production_tracking',
        'schedule': 86400.0,  # Toutes les 24 heures
    },
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gest_coop.urls'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Répertoire global des templates        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gest_coop.wsgi.application'

AUTH_USER_MODEL = 'authentication.CustomUser'



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gestcoopagri',
        'USER': 'abdoul',
        'PASSWORD': 'Pierre74Az@',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Paramètres de session
SESSION_COOKIE_AGE = 1209600  # Deux semaines
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
