# Generated by Django 5.1.1 on 2024-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('manager', 'Gestionnaire'), ('worker', 'Ouvrier'), ('advisor', 'Conseiller'), ('technician', 'Technicien'), ('accountant', 'Comptable'), ('supervisor', 'Superviseur'), ('logistics', 'Logisticien'), ('driver', 'Chauffeur'), ('trainer', 'Formateur'), ('security', 'Sécurité'), ('agriculteur', 'Agriculteur')], max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
