# Generated by Django 5.1.1 on 2024-10-02 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('sésame', 'Sésame'), ('maïs', 'Maïs'), ('mil', 'Mil'), ('sorgho', 'Sorgho'), ('riz', 'Riz'), ('arachide', 'Arachide'), ('coton', 'Coton'), ('niébé', 'Niébé'), ('gombo', 'Gombo'), ('tomate', 'Tomate'), ('oignon', 'Oignon'), ('igname', 'Igname')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantité produite (en tonnes)', max_digits=10)),
                ('production_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('sésame', 'Sésame'), ('maïs', 'Maïs'), ('mil', 'Mil'), ('sorgho', 'Sorgho'), ('riz', 'Riz'), ('arachide', 'Arachide'), ('coton', 'Coton'), ('niébé', 'Niébé'), ('gombo', 'Gombo'), ('tomate', 'Tomate'), ('oignon', 'Oignon'), ('igname', 'Igname')], max_length=50)),
                ('prediction_date', models.DateField()),
                ('predicted_quantity', models.DecimalField(decimal_places=2, help_text='Quantité prédite (en tonnes)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
