# Generated by Django 5.1.1 on 2024-10-02 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionprediction',
            name='user',
        ),
        migrations.CreateModel(
            name='ProductionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('type_culture', models.CharField(choices=[('sésame', 'Sésame'), ('maïs', 'Maïs'), ('mil', 'Mil'), ('sorgho', 'Sorgho'), ('riz', 'Riz'), ('arachide', 'Arachide'), ('coton', 'Coton'), ('niébé', 'Niébé'), ('gombo', 'Gombo'), ('tomate', 'Tomate'), ('oignon', 'Oignon'), ('igname', 'Igname')], max_length=50)),
                ('date_prevue_semer', models.DateField(blank=True, null=True)),
                ('date_mise_engrais', models.DateField(blank=True, null=True)),
                ('quantite_engrais', models.DecimalField(blank=True, decimal_places=2, help_text="Quantité d'engrais en kg", max_digits=10, null=True)),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionEntry',
        ),
        migrations.DeleteModel(
            name='ProductionPrediction',
        ),
    ]
